# Generated by Django 5.1.4 on 2024-12-15 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('school_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('International', 'International'), ('Religious', 'Religious'), ('Charter', 'Charter'), ('Montessori', 'Montessori'), ('Homeschool', 'Homeschool'), ('Specialized', 'Specialized'), ('Alternative', 'Alternative')], max_length=100)),
                ('open_at', models.DateField(default=django.utils.timezone.now)),
                ('grade_offer', models.CharField(choices=[('Preschool', 'Preschool'), ('Elementary School', 'Grades K-5'), ('Middle School', 'Grades 6-8'), ('High School', 'Grades 9-12'), ('Kindergarten', 'Kindergarten'), ('K-12', 'KG to Grade 12')], max_length=100)),
                ('event_data', models.ManyToManyField(blank=True, to='api.event')),
                ('students_data', models.ManyToManyField(blank=True, to='api.studentinfo')),
                ('teachers_data', models.ManyToManyField(blank=True, to='api.teacherinfo')),
            ],
        ),
    ]
