# Generated by Django 5.1.4 on 2024-12-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_principalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overview',
            name='event_data',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='students_data',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='teachers_data',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Absent', max_length=10),
        ),
    ]
